### ISSUE TITLE
Panic in wasmtime in `t/wasm_wasmtime_func.t` test on aarch64

### ISSUE THREAD

**Issue by plicease** [perlwasm/Wasm#58]
This happens with both wasmtime 0.16.0 and dev (as of at least https://github.com/bytecodealliance/wasmtime/commit/8f2d442ffd852d40f128b4c00830279aad894e09)

```
pi1% env RUST_BACKTRACE=1 prove -lvm t/wasm_wasmtime_func.t 
t/wasm_wasmtime_func.t .. 
ok 1 - function add
ok 2 - call add
ok 3 - attached using caller
ok 4 - calling attached Foo::Bar::baz
ok 5 - warns about redefine
ok 6 - attached using caller
ok 7 - calling attached Foo::Bar::optimus
ok 8 - attach using explicit package does not install in caller
ok 9 - attach using explicit package
ok 10 - calling attached Bar::baz
thread '<unnamed>' panicked at 'not implemented', cranelift/codegen/src/isa/aarch64/abi.rs:1268:18
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: std::panicking::begin_panic
  12: cranelift_codegen::isa::aarch64::lower_inst::lower_insn_to_regs
  13: cranelift_codegen::machinst::lower::Lower<I>::lower
  14: <cranelift_codegen::isa::aarch64::AArch64Backend as cranelift_codegen::machinst::MachBackend>::compile_function
  15: cranelift_codegen::context::Context::compile
  16: cranelift_codegen::context::Context::compile_and_emit
  17: wasmtime_jit::compiler::make_trampoline
  18: wasmtime_jit::compiler::Compiler::compile
  19: wasmtime_jit::instantiate::CompiledModule::new
  20: wasmtime::module::Module::from_binary_unchecked
  21: wasmtime::module::Module::from_binary
  22: wasmtime_module_new
  23: <unknown>
  24: <unknown>
  25: ffi_pl_sub_call
  26: Perl_pp_entersub
  27: Perl_runops_standard
  28: perl_run
  29: main
  30: __libc_start_main
  31: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 3522684192
All 10 subtests passed 

Test Summary Report
-------------------
t/wasm_wasmtime_func.t (Wstat: 134 Tests: 10 Failed: 0)
  Non-zero wait status: 134
  Parse errors: No plan found in TAP output
Files=1, Tests=10,  1 wallclock secs ( 0.05 usr  0.03 sys +  0.62 cusr  0.13 csys =  0.83 CPU)
Result: FAIL
```

**Comment by plicease** [comment]
Short test that triggers the panic:

```perl
use Test2::V0 -no_srand => 1;
use Wasm::Wasmtime;

my $instance = Wasm::Wasmtime::Instance->new(
  Wasm::Wasmtime::Module->new(
    wat => q{
      (module
        (func $round_trip_many
          (export "round_trip_many")
          (param i64 i64 i64 i64 i64 i64 i64 i64 i64 i64)
          (result i64 i64 i64 i64 i64 i64 i64 i64 i64 i64)
          local.get 0
          local.get 1
          local.get 2
          local.get 3
          local.get 4
          local.get 5
          local.get 6
          local.get 7
          local.get 8
          local.get 9
        )
      )
    }
  ),
);

is(
  $instance->exports->round_trip_many->call(0,1,2,3,4,5,6,7,8,9),
  [0,1,2,3,4,5,6,7,8,9],
);

done_testing;
```

**Comment by plicease** [comment]
This appears to be either a bug or unimplemented feature in wasmtime itself.

**Comment by plicease** [comment]
Fixed in wasmtime 🎉
